#! /bin/sh

tab="$(printf '\t')"

_help () {
	cat <<-EOF
	usage: ${0} <action> [cards] [level] [state]

	action:
	${tab}get       (get DPM profile from selected cards)
	${tab}set       (set DPM profile on selected cards)
	${tab}help      (print this help)

	cards:
	${tab}all       (default}
	${tab}0
	${tab}0,1

	level:
	${tab}auto      (default)
	${tab}low
	${tab}high

	state:
	${tab}balanced  (default)
	${tab}battery
	${tab}performance

	EOF

	exit 0
}

_logger () {
	while read line
	do
		printf '%s\n' "${line}"
		if [ -z "${AS_SERVICE}" ]
		then
			printf '%s\n' "${line}" | logger -t "$(basename "${0}")" | 2>&1
		fi
	done
}

_test_card () {
	[ -d "/sys/class/drm/card${1}" ]
}

_test_dpm_available () {
	[ -f "/sys/class/drm/card${1}/device/power_method" ]
}

_test_dpm_enabled () {
	[ "$(cat "/sys/class/drm/card${1}/device/power_method")" = 'dpm' ]
}

_check_card () {
	if ! _test_card "${1}"
	then
		printf 'ERROR: missing card%s\n' "${1}" | _logger
		exit 11
	fi
}

_check_dpm () {
	if ! _test_dpm_available "${1}"
	then
		printf 'ERROR: dpm not available\n' | _logger
		exit 12
	elif ! _test_dpm_enabled "${1}"
	then
		printf 'ERROR: dpm not enabled\n' | _logger
		exit 13
	fi
}

_list_cards () {
	case "${1}" in
		'all')
			for card in $(ls -d '/sys/class/drm/card'[0-9] | cut -c20-)
			do
				if _test_dpm_available "${card}"
				then
					if _test_dpm_enabled "${card}"
					then
						printf '%s\n' "${card}"
					fi
				fi
			done
		;;
		*)
			echo "${1}" | tr ',' '\n'
		;;
	esac
}

_get () {
	printf 'card%s/%s: "%s"\n' "${1}" "${2}" "$(cat "/sys/class/drm/card${1}/device/${2}")" | _logger
}

_set () {
	if echo "${3}" > "/sys/class/drm/card${1}/device/${2}"
	then
		printf 'card%s/%s="%s"\n' "${1}" "${2}" "${3}" | _logger
		true
	else
		printf 'ERROR: card%s/%s does not accept "%s"\n' "${1}" "${2}" "${3}" | _logger
		false
	fi
}

case "${1}" in
	'get')
		cards="${2:-0}"
		for card in $(_list_cards "${cards}")
		do
			_check_card "${card}"
			_check_dpm "${card}"
		
			_get "${card}" 'power_dpm_force_performance_level' || exit 21
			_get "${card}" 'power_dpm_state' || exit 22
		done
	;;
	'set')
		cards="${2:-0}"
		for card in $(_list_cards "${cards}")
		do
			_check_card "${card}"
			_check_dpm "${card}"

			level="${3:-auto}"
			state="${4:-balanced}"
			_set "${card}" 'power_dpm_force_performance_level' "${level}" || exit 31
			_set "${card}" 'power_dpm_state' "${state}" || exit 32
		done
	;;
	*)
		_help
	;;
esac

#EOF
